services:
  # Overriding base DB to fix healthcheck syntax and provide the 'db' network alias
  transcendence_db:
    healthcheck:
      test: mariadb-admin ping -h localhost -u root -p$$MARIADB_ROOT_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      default:
        aliases:
          - db # Matches the hostname expected by the App container

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: transcendence_app
    restart: on-failure
    env_file:
      - .env
    environment:
      # Connects via the internal Docker 'db' alias
      - DATABASE_URL=mysql://${MARIADB_USER}:${MARIADB_PASSWORD}@db:3306/${MARIADB_DATABASE}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - NEXTAUTH_TRUSTHOST=true # Trusts Nginx headers for Server Actions
    depends_on:
      transcendence_db:
        condition: service_healthy

  nginx:
    build:
      context: ./docker/nginx
    container_name: transcendence_nginx
    restart: on-failure
    ports:
      - "8443:443"
      - "8080:80"
    depends_on:
      - app
