# Non-containerized dev mode, only use a container for mariadb and run node/nextjs/tools outside

services:
  transcendence_db:
    extends:
      file: docker/mariadb.yml
      service: mariadb
    container_name: transcendence_db
    # Expose the DB port for standalone use
    ports:
      - "3306:3306"

volumes:
  transcendence_mariadb_data:
