// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Prisma CLI needs to be able to create a shadow database for migrations, so connect as root
const user = "root";
const {
  MARIADB_ROOT_PASSWORD: password,
  MARIADB_HOST: host,
  MARIADB_DATABASE: database,
} = process.env;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: `mysql://${user}:${password}@${host}:3306/${database}`,
  },
});
