import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Providers } from "@/components/Providers";
import { cookies } from "next/headers";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const cookieStore = await cookies();
  const dark = cookieStore.get("dark")?.value === "true";
  const lang = cookieStore.get("lang")?.value ?? "en";

  return (
    <html className={dark ? "dark" : ""}>
      <body
        className={`bg-gradient-to-br from-purple-light to-blue-light ${geistSans.variable} ${geistMono.variable}`}
      >
        <Providers initialLang={lang}>
          <div className="h-screen flex flex-col">
            <div className="pt-5 px-5">
              <Header />
            </div>
            <div className="text-text text-3xl flex-1 flex flex-col justify-center mx-5 my-3 rounded-xl text-center overflow-hidden">
              {children}
            </div>
            <div className="pb-5 px-5">
              <Footer initialDark={dark} />
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
